### ISSUE TITLE
How to use AsyncWaitGroup?

### ISSUE THREAD

**Issue by scripturial** [al8n/wg#3]
This is just copied from the code file/documentation for reference:
 
```
/// use wg::AsyncWaitGroup;
/// use std::sync::Arc;
/// use std::sync::atomic::{AtomicUsize, Ordering};
/// use tokio::{spawn, time::{sleep, Duration}};

```

How do you import `AsyncWaitGroup`? Neither of these work?

```
10 | use wg::AsyncWaitGroup;
   |     ^^^^^^^^^^^^^^^^^^ no `AsyncWaitGroup` in the root

use wg::async::AsyncWaitGroup;
   |         ^^^^^ could not find `r#async` in `wg`


```

**Comment by scripturial** [comment]
I wound back to version 0.3 and the example code works. So there is something not quite right in my combination of rust, and the latest version, and the example code.

**Comment by al8n** [comment]
Hi, you should add `future` feature in Cargo.toml to enable AsyncWaitGroup.
